### PR TITLE
Feature: Added Create Announcement Button (Placeholder Page)

### LINKED ISSUE #49: Feature: Create Announcements Button (Placeholder Page)
# Feature: Show Announcements on Index Page (Frontend)

User story:
* As an admin
* I can click the `Create Announcement` button and it lead to the placeholder page

Acceptance Criteria:

- [x] When you click the `Create Announcement` button, it leads you to the placeholder page
- [x] The url in the search bar is correct on the placeholder page

### PR DESCRIPTION
**Pull request by jasontnguyen**
## Overview

In this PR, I added a create announcement button on the announcements index page that will lead you to a placeholder page saying the feature is coming soon (implemented in different issue)

## Merge Info
- This PR requires PR #48 first since it requires corrected backend changes in that PR request. I rebased this branch off main first.

## Screenshots

Screenshot 2024-05-25 at 2 03 37 AM
Screenshot 2024-05-25 at 2 03 52 AM

## Future Possibilities 

- This is the beginning/part of allowing the user to actually create an announcement through the fronted and not through swagger.

## Validation 

1. Rebuild my dokku dev app by doing `dokku git:sync happycows-jasontnguyen-dev https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5.git JN-CreateButton` then `dokku ps:rebuild happycows-jasontnguyen-dev`
2. Use my dokku link: https://happycows-jasontnguyen-dev.dokku-05.cs.ucsb.edu
3. Create a new commons and go to List Commons in the admin tab
4. Click the Announcements button and it leads you to the index page
5. Check if the url matches the commons id in the search bar and that the create announcements button leads to the placeholder page

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #49

### CODE REVIEW

**Comment by winstonwangUCSB** [comment]
Tests work, create announcement button exists and brings you to placeholder page on dokku when clicked. Everything matches PR description. LGTM.

**Review by winstonwang120 — DISMISSED** [review]
Tests work, create announcement button exists and brings you to placeholder page on dokku when clicked. Everything matches PR description. LGTM.

**Review by CongruiDu — DISMISSED** [review]
LGTM, I can see the create announcement button and the placeholder page with the dokku link

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
