### PR TITLE
Updated pom.xml so partial pitest runs work

### LINKED ISSUE #44: Issue: Update pom.xml for Partial Pitest runs
Description : Add incremental pitest to this project.

- [ ] Make it possible to run `mvn pitest:mutationCoverage` on just a single class, or a single package, instead of the entire backend code base

### PR DESCRIPTION
**Pull request by nevetsle**
## Overview

In this PR, we updated the pom.xml so it's possible to run 'mvn pitest:mutationCoverage' on just a single class, or just a single package, instead of the entire backend code base.

## Screenshots

On Controllers Package:
Screen Shot 2024-05-24 at 8 46 00 PM

On only Commons Controller:
Screen Shot 2024-05-24 at 8 56 58 PM

On Api Controller:

Screen Shot 2024-05-24 at 9 07 13 PM

## Validation 

1. Download this branch.
2. Run the commands from the test section below
3. Verify that the mutations are all accounted for with all tests passing

## Tests

- [ ] Backend Commons Controller Pitest coverage (`mvn pitest:mutationCoverage -DtargetClasses=edu.ucsb.cs156.happiercows.controllers.CommonsController`) pass
- [ ] Backend All Controllers Pitest coverage (`mvn pitest:mutationCoverage -DtargetClasses=edu.ucsb.cs156.example.controllers.`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Backend API Controller Pitest coverage ('mvn pitest:mutationCoverage -DtargetClasses=edu.ucsb.cs156.happiercows.controllers.ApiController') pass

## Linked Issues

Closes #44

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
This is good. But please also add the changes to the README.md from the original PR, adapting them to proj-happycows.

**Comment by nevetsle** [comment]
> This is good. But please also add the changes to the README.md from the original PR, adapting them to proj-happycows.

README.md has been updated with according changes

**Review by pconrad — APPROVED** [review]
LGTM

**Review by GarvinYoung — APPROVED** [review]
LGTM, ran all the tests and they worked

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
