### PR TITLE
Feature: Endpoints for Suspending and Restoring Users

### LINKED ISSUE #41: Issue B2: Add endpoints that suspend or restore user
Simple issue that just adds an endpoint in the Users controller that is accessible only to Admins.

- [x] POST /users/suspend/{userid} sets the suspended field to true

- [x] POST /users/restore/{userid} sets the suspended field to false

You can look at organic and gauchoride for the toggle admin endpoints for code that would be similar to this.

### PR DESCRIPTION
**Pull request by winstonwang120**
Adds endpoints for suspending and restoring users.

**Merge Info:**
Merge after PR #59 

**Screenshots:**
Screenshot 2024-05-27 at 5 22 14 PM
Screenshot 2024-05-27 at 5 22 25 PM

**Validation:**
Dokku deployment at [https://happycows-winstonwang-dev.dokku-05.cs.ucsb.edu/](https://happycows-winstonwang-dev.dokku-05.cs.ucsb.edu/)
Test endpoints using swagger after logging in: [https://happycows-winstonwang-dev.dokku-05.cs.ucsb.edu/swagger-ui/index.html#/](https://happycows-winstonwang-dev.dokku-05.cs.ucsb.edu/swagger-ui/index.html#/)

**Tests:**
Backend Unit tests (mvn test) pass
Backend Test coverage (mvn test jacoco:report) 100%
Backend Mutation tests (mvn test pitest:mutationCoverage) 100%

Closes #41

### CODE REVIEW

**Review by jasontnguyen — DISMISSED** [review]
LGTM, the endpoints work on swagger and I verified the suspended variable using get all users endpoint.

**Review by Baimin-Wang — DISMISSED** [review]
LGTM!

**Comment by winstonwang120** [comment]
Fixed Merge conflict. It was just whitespace issue.

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
