### PR TITLE
Show List of Announcements For Certain Commons

### LINKED ISSUE #47: Feature: Show Announcements on Index Page
# Feature: Show Announcements on Index Page (Frontend)

User story:
* As an admin
* I can create a new announcement and will show in the table of the announcements page

Acceptance Criteria:

- [x] On Swagger, when you create a new announcement, it should return the correct information
- [x] When you check the frontend page for the announcements, the newly created announcement shows up for the correct commons

### PR DESCRIPTION
**Pull request by jasontnguyen**
## Overview

In this PR, we add an table on the Announcements Index Page that allows an admin to look at all the current announcements for a certain commons. The table will be different for each commons.

## UPDATE
I added a max width CSS property so it handles long announcement texts.
Screenshot 2024-05-26 at 6 49 32 PM

## Screenshots 

Screenshot 2024-05-25 at 12 38 47 AM

## Future Possibilities 

Some possible points could be:
- This is the beginning/part of allowing the admin user to create, edit, and delete based on the info in the table
- Could be improved by allowing the user to see a default view of the ids in descending order

## Validation 

1. Rebuild my dokku dev app by doing `dokku git:sync happycows-jasontnguyen-dev https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-5.git JN-ShowAnnouncementsTable` then `dokku ps:rebuild happycows-jasontnguyen-dev`
2. Use my dokku link: https://happycows-jasontnguyen-dev.dokku-05.cs.ucsb.edu
3. Create a new announcement for a certain commons through Swagger
4. Go back to the announcements page for that common and check that the announcement shows up

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #47

### CODE REVIEW

**Review by pconrad — DISMISSED** [review]
Please consider adding a max width CSS property to the column for the announcment text so that we don't get this:
overflowing-announcements

Another option would be a list of cards instead of a table, using the React Bootstrap "Card" element. It would be similar to the layout on the  page where users select a commons to visit or join.

If you make a new issue for that and put it in the backlog, I'm happy to go ahead and approve this; that way you get 1the points right away and you get 5 more when you merge the fix.  Or you can do it in this PR and I'll add a 5 point bonus.

**Review by GarvinYoung — DISMISSED** [review]
LGTM, table correctly displays all announcement fields and announcement emssage wraps for long messages.

**Review by nevetsle — DISMISSED** [review]
After checking on dokku, I was able to see the list of announcements for each respective common. LGTM!

**Review by pconrad — DISMISSED** [review]
LGTM

**Pull request merged**
